[build]
  command = "npm i && cd api && npm i && cd ../web-react && npm i && cd .. && npm run build && cp api/build/graphql-schema.js api/build/functions/graphql/. && cp api/build/schema.graphql api/build/functions/graphql/.  && cd api/src/functions/graphql && npm i"
  publish = "web-react/build"
  functions = "api/build/functions"

[dev]
  command = "npm start"

[template.environment]
  NEO4J_URI = "bolt://35.234.149.240:7687/graphql"
  NEO4J_USER = "neo4j"
  NEO4J_PASSWORD = "72fofH0oav"
  REACT_APP_AUTH0_CLIENT_ID = "w5Gj6j1S4SKDiH3l7CmQqEtXxzxt8xQ0"
  REACT_APP_AUTH0_DOMAIN = "mems.eu.auth0.com"
  
[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/*"
  to =  "/404"
  status = "200"