type Mem {
  memID: ID!
  mem: String
  date: Date
  memType: String
  emoji: String
  pictures: String
  personID: [Int]
  placeID: [Int]
  person: [Person] @relation(name: "WITH", direction: OUT)
  place: [Place] @relation(name: "AT", direction: OUT)
  music: [Music] @relation(name: "LISTENED_TO", direction: OUT)
  movie: [Movie] @relation(name: "WATCHED", direction: OUT)
  tvshow: [TVShow] @relation(name: "WATCHED", direction: OUT)
  game: [Game] @relation(name: "PLAYED", direction: OUT)
}

type Person {
  personID: ID!
  nickname: String
  firstName: String
  lastName: String
  mem: [Mem] @relation(name: "WITH", direction: IN)
}

type Place {
  placeID: ID!
  place: String
  city: String
  postcode: String
  location: String
  notes: String
  mem: [Mem] @relation(name: "AT", direction: IN)
}

type Music {
  musicID: ID!
  album: String
  Artist: String
  releaseDate: Date
  genre: String
  style: String
  albumArt: String
  wikipediaPage: String
  mem: [Mem] @relation(name: "LISTENED_TO", direction: IN)
}

type Movie {
  movieID: ID!
  movie: String
  releaseDate: String
  synopsis: String
  director: String
  imdbRating: Float
  poster: String
  mem: [Mem] @relation(name: "WATCHED", direction: IN)
}

type TVShow {
  tvshowID: ID!
  tvshow: String
  releaseDate: Date
  creator: String
  synopsis: String
  poster: String
  wikipediaPage: String
  mem: [Mem] @relation(name: "WATCHED", direction: IN)
}

type Game {
  gameID: ID!
  game: String
  releaseDate: Date
  developer: String
  description: String
  boxArt: String
  wikipediaPage: String
  mem: [Mem] @relation(name: "PLAYED", direction: IN)
}

type Query {
  memCount: Int! @cypher(statement: "MATCH (m:Mem) RETURN COUNT(m)")
  peopleCount: Int! @cypher(statement: "MATCH (m:Person) RETURN COUNT(m)")
  placeCount: Int! @cypher(statement: "MATCH (m:Place) RETURN COUNT(m)")
  musicCount: Int! @cypher(statement: "MATCH (m:Music) RETURN COUNT(m)")
  movieCount: Int! @cypher(statement: "MATCH (m:Movie) RETURN COUNT(m)")
  tvshowCount: Int! @cypher(statement: "MATCH (m:TVShow) RETURN COUNT(m)")
  gameCount: Int! @cypher(statement: "MATCH (m:Game) RETURN COUNT(m)")
}